using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using Dapper;
using ExistsForAll.DapperExtensions.Mapper;
using ExistsForAll.DapperExtensions.Sql;

namespace ExistsForAll.DapperExtensions
{
	public class DapperImplementor : IDapperImplementor
	{
		private IClassMapperRepository ClassMappers { get; }
		private IDapperExtensionsConfiguration Configuration { get; }

		public DapperImplementor(ISqlGenerator sqlGenerator,
			IClassMapperRepository classMappers,
			IDapperExtensionsConfiguration dapperExtensionsConfiguration)
		{
			ClassMappers = classMappers;
			Configuration = dapperExtensionsConfiguration;
			SqlGenerator = sqlGenerator;
		}

		private ISqlGenerator SqlGenerator { get; }

		public T Get<T>(IDbConnection connection, object id, IDbTransaction transaction, int? commandTimeout) where T : class
		{
			var classMap = ClassMappers.GetMap<T>();
			var predicate = classMap.GetIdPredicate(id);
			var result = GetList<T>(connection, classMap, predicate, null, transaction, commandTimeout, true).SingleOrDefault();
			return result;
		}

		public void Insert<T>(IDbConnection connection,
			IEnumerable<T> entities,
			IDbTransaction transaction,
			int? commandTimeout) where T : class
		{
			var classMap = ClassMappers.GetMap<T>();

			var parameters = new List<DynamicParameters>();

			var columns = classMap.GetMutableColumns();

			var autoGeneratedProperty = classMap.GetAutoGeneratedId();

			foreach (var e in entities)
			{
				//foreach (var column in keys)
				//{
				//	// todo : deal with GUID self generated. 
				//	if (column.KeyType == KeyType.Guid && (Guid) column.PropertyInfo.GetValue(e, null) == Guid.Empty)
				//	{
				//		Guid comb = Configuration.GetNextGuid();
				//		column.PropertyInfo.SetValue(e, comb, null);
				//	}
				//}

				var dynamicParameters = new DynamicParameters();

				foreach (var column in columns)
				{
					dynamicParameters.Add(column.Name, column.Getter(e));
				}

				if (autoGeneratedProperty != null)
				{
					var defaultValue = autoGeneratedProperty.Getter(e);
					dynamicParameters.Add("IdOutParam", direction: ParameterDirection.Output, value: defaultValue);
				}

				parameters.Add(dynamicParameters);
			}

			var sql = SqlGenerator.InsertBatch(classMap);

			connection.Execute(sql, parameters, transaction, commandTimeout, CommandType.Text);
		}

		public void Insert<T>(IDbConnection connection, T entity, IDbTransaction transaction, int? commandTimeout)
			where T : class
		{
			var classMap = ClassMappers.GetMap<T>();

			var columns = classMap.GetMutableColumns();

			var autoGeneratedProperty = classMap.GetAutoGeneratedId();

			//foreach (var column in nonIdentityKeyProperties)
			//{
			//	if (column.KeyType == KeyType.Guid && (Guid)column.PropertyInfo.GetValue(entity, null) == Guid.Empty)
			//	{
			//		Guid comb = Configuration.GetNextGuid();
			//		column.PropertyInfo.SetValue(entity, comb, null);
			//	}
			//}

			var sql = SqlGenerator.Insert(classMap);

			if (autoGeneratedProperty != null)
			{
				IEnumerable<long> result;
				if (SqlGenerator.SupportsMultipleStatements())
				{
					sql += Configuration.Dialect.BatchSeperator + SqlGenerator.IdentitySql(classMap);
					result = connection.Query<long>(sql, entity, transaction, false, commandTimeout, CommandType.Text);
				}
				else
				{
					connection.Execute(sql, entity, transaction, commandTimeout, CommandType.Text);
					sql = SqlGenerator.IdentitySql(classMap);
					result = connection.Query<long>(sql, entity, transaction, false, commandTimeout, CommandType.Text);
				}

				autoGeneratedProperty.Setter(entity, result);
				return;
			}

			connection.Execute(sql, entity, transaction, commandTimeout, CommandType.Text);
		}

		public bool Update<T>(IDbConnection connection, T entity, IDbTransaction transaction, int? commandTimeout,
			bool ignoreAllKeyProperties = false) where T : class
		{
			var classMap = ClassMappers.GetMap<T>();
			var predicate = GetKeyPredicate<T>(classMap, entity);
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.Update(classMap, predicate, parameters, ignoreAllKeyProperties);
			var dynamicParameters = new DynamicParameters();

			var columns = classMap.GetMutableColumns();

			foreach (var property in XExtensions.GetObjectValues(entity)
				.Where(property => columns.Any(c => c.Name == property.Key)))
			{
				dynamicParameters.Add(property.Key, property.Value);
			}

			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return connection.Execute(sql, dynamicParameters, transaction, commandTimeout, CommandType.Text) > 0;
		}

		public bool Delete<T>(IDbConnection connection, T entity, IDbTransaction transaction, int? commandTimeout)
			where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var predicate = GetKeyPredicate<T>(classMap, entity);
			return Delete<T>(connection, classMap, predicate, transaction, commandTimeout);
		}

		public bool Delete<T>(IDbConnection connection, object predicate, IDbTransaction transaction, int? commandTimeout)
			where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var wherePredicate = GetPredicate(classMap, predicate);
			return Delete<T>(connection, classMap, wherePredicate, transaction, commandTimeout);
		}

		public IEnumerable<T> GetList<T>(IDbConnection connection, object predicate, IList<ISort> sort,
			IDbTransaction transaction, int? commandTimeout, bool buffered) where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var wherePredicate = GetPredicate(classMap, predicate);
			return GetList<T>(connection, classMap, wherePredicate, sort, transaction, commandTimeout, buffered);
		}

		public IEnumerable<T> GetPage<T>(IDbConnection connection, object predicate, IList<ISort> sort, int page,
			int resultsPerPage, IDbTransaction transaction, int? commandTimeout, bool buffered) where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var wherePredicate = GetPredicate(classMap, predicate);
			return GetPage<T>(connection, classMap, wherePredicate, sort, page, resultsPerPage, transaction, commandTimeout,
				buffered);
		}

		public IEnumerable<T> GetSet<T>(IDbConnection connection, object predicate, IList<ISort> sort, int firstResult,
			int maxResults, IDbTransaction transaction, int? commandTimeout, bool buffered) where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var wherePredicate = GetPredicate(classMap, predicate);
			return GetSet<T>(connection, classMap, wherePredicate, sort, firstResult, maxResults, transaction, commandTimeout,
				buffered);
		}

		public int Count<T>(IDbConnection connection, object predicate, IDbTransaction transaction, int? commandTimeout)
			where T : class
		{
			IClassMapper classMap = ClassMappers.GetMap<T>();
			var wherePredicate = GetPredicate(classMap, predicate);
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.Count(classMap, wherePredicate, parameters);
			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return (int)connection.Query(sql, dynamicParameters, transaction, false, commandTimeout, CommandType.Text).Single()
				.Total;
		}

		public IMultipleResultReader GetMultiple(IDbConnection connection, GetMultiplePredicate predicate,
			IDbTransaction transaction, int? commandTimeout)
		{
			if (SqlGenerator.SupportsMultipleStatements())
			{
				return GetMultipleByBatch(connection, predicate, transaction, commandTimeout);
			}

			return GetMultipleBySequence(connection, predicate, transaction, commandTimeout);
		}

		protected IEnumerable<T> GetList<T>(IDbConnection connection,
			IClassMapper classMap,
			IPredicate predicate,
			IList<ISort> sort,
			IDbTransaction transaction,
			int? commandTimeout,
			bool buffered) where T : class
		{
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.Select(classMap, predicate, sort, parameters);

			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return connection.Query<T>(sql, dynamicParameters, transaction, buffered, commandTimeout, CommandType.Text);
		}

		protected IEnumerable<T> GetPage<T>(IDbConnection connection, IClassMapper classMap, IPredicate predicate,
			IList<ISort> sort, int page, int resultsPerPage, IDbTransaction transaction, int? commandTimeout, bool buffered)
			where T : class
		{
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.SelectPaged(classMap, predicate, sort, page, resultsPerPage, parameters);
			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return connection.Query<T>(sql, dynamicParameters, transaction, buffered, commandTimeout, CommandType.Text);
		}

		protected IEnumerable<T> GetSet<T>(IDbConnection connection, IClassMapper classMap, IPredicate predicate,
			IList<ISort> sort, int firstResult, int maxResults, IDbTransaction transaction, int? commandTimeout, bool buffered)
			where T : class
		{
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.SelectSet(classMap, predicate, sort, firstResult, maxResults, parameters);
			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return connection.Query<T>(sql, dynamicParameters, transaction, buffered, commandTimeout, CommandType.Text);
		}

		protected bool Delete<T>(IDbConnection connection, IClassMapper classMap, IPredicate predicate,
			IDbTransaction transaction, int? commandTimeout) where T : class
		{
			var parameters = new Dictionary<string, object>();
			var sql = SqlGenerator.Delete(classMap, predicate, parameters);
			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			return connection.Execute(sql, dynamicParameters, transaction, commandTimeout, CommandType.Text) > 0;
		}

		protected IPredicate GetPredicate(IClassMapper classMap, object predicate)
		{
			var wherePredicate = predicate as IPredicate;
			if (wherePredicate == null && predicate != null)
			{
				wherePredicate = GetEntityPredicate(classMap, predicate);
			}

			return wherePredicate;
		}

		

		protected IPredicate GetKeyPredicate<T>(IClassMapper classMap, T entity) where T : class
		{
			var whereFields = classMap.Keys;

			if (!whereFields.Any())
			{
				throw new ArgumentException("At least one Key column must be defined.");
			}

			IList<IPredicate> predicates = (from field in whereFields
											select new FieldPredicate<T>
											{
												Not = false,
												Operator = Operator.Eq,
												PropertyName = field.Name,
												Value = field.PropertyInfo.GetValue(entity, null)
											}).Cast<IPredicate>().ToList();

			return predicates.Count == 1
				? predicates[0]
				: new PredicateGroup
				{
					Operator = GroupOperator.And,
					Predicates = predicates
				};
		}

		protected IPredicate GetEntityPredicate(IClassMapper classMap, object entity)
		{
			var predicateType = typeof(FieldPredicate<>).MakeGenericType(classMap.EntityType);
			IList<IPredicate> predicates = new List<IPredicate>();
			foreach (var kvp in XExtensions.GetObjectValues(entity))
			{
				var fieldPredicate = Activator.CreateInstance(predicateType) as IFieldPredicate;
				fieldPredicate.Not = false;
				fieldPredicate.Operator = Operator.Eq;
				fieldPredicate.PropertyName = kvp.Key;
				fieldPredicate.Value = kvp.Value;
				predicates.Add(fieldPredicate);
			}

			return predicates.Count == 1
				? predicates[0]
				: new PredicateGroup
				{
					Operator = GroupOperator.And,
					Predicates = predicates
				};
		}

		protected GridReaderResultReader GetMultipleByBatch(IDbConnection connection, GetMultiplePredicate predicate,
			IDbTransaction transaction, int? commandTimeout)
		{
			var parameters = new Dictionary<string, object>();
			var sql = new StringBuilder();
			foreach (var item in predicate.Items)
			{
				IClassMapper classMap = ClassMappers.GetMap(item.Type);
				var itemPredicate = item.Value as IPredicate;
				if (itemPredicate == null && item.Value != null)
				{
					itemPredicate = GetPredicate(classMap, item.Value);
				}

				sql.AppendLine(SqlGenerator.Select(classMap, itemPredicate, item.Sort, parameters) +
							   Configuration.Dialect.BatchSeperator);
			}

			var dynamicParameters = new DynamicParameters();
			foreach (var parameter in parameters)
			{
				dynamicParameters.Add(parameter.Key, parameter.Value);
			}

			var grid = connection.QueryMultiple(sql.ToString(), dynamicParameters, transaction, commandTimeout,
				CommandType.Text);
			return new GridReaderResultReader(grid);
		}

		protected SequenceReaderResultReader GetMultipleBySequence(IDbConnection connection, GetMultiplePredicate predicate,
			IDbTransaction transaction, int? commandTimeout)
		{
			IList<SqlMapper.GridReader> items = new List<SqlMapper.GridReader>();
			foreach (var item in predicate.Items)
			{
				var parameters = new Dictionary<string, object>();
				IClassMapper classMap = ClassMappers.GetMap(item.Type);
				var itemPredicate = item.Value as IPredicate;
				if (itemPredicate == null && item.Value != null)
				{
					itemPredicate = GetPredicate(classMap, item.Value);
				}

				var sql = SqlGenerator.Select(classMap, itemPredicate, item.Sort, parameters);
				var dynamicParameters = new DynamicParameters();
				foreach (var parameter in parameters)
				{
					dynamicParameters.Add(parameter.Key, parameter.Value);
				}

				var queryResult = connection.QueryMultiple(sql, dynamicParameters, transaction, commandTimeout, CommandType.Text);
				items.Add(queryResult);
			}

			return new SequenceReaderResultReader(items);
		}
	}
}
