namespace ExistsForAll.DapperExtensions.UnitTests.Mapping
{
	public class AutoGeneratedLongEntityMapper : BaseMapper<IntEntity>
	{
		public AutoGeneratedLongEntityMapper()
		{
			Key(x => x.Id).GeneratedBy.AutoGenerated();
		}
	}
}