using System.Reflection;

namespace ExistsForAll.DapperExtensions.Mapper
{
	/// <summary>
	/// Maps an entity property to its corresponding column in the database.
	/// </summary>
	public class PropertyMap : IPropertyMap
	{
		public PropertyMap(PropertyInfo propertyInfo)
		{
			PropertyInfo = propertyInfo;
			ColumnName = PropertyInfo.Name;
		}

		/// <summary>
		/// Gets the name of the property by using the specified propertyInfo.
		/// </summary>
		public string Name => PropertyInfo.Name;

		/// <summary>
		/// Gets the column name for the current property.
		/// </summary>
		public string ColumnName { get; private set; }

		/// <summary>
		/// Gets the ignore status of the current property. If ignored, the current property will not be included in queries.
		/// </summary>
		public bool Ignored { get; private set; }

		/// <summary>
		/// Gets the read-only status of the current property. If read-only, the current property will not be included in INSERT and UPDATE queries.
		/// </summary>
		public bool IsReadOnly { get; private set; }

		/// <summary>
		/// Gets the property info for the current property.
		/// </summary>
		public PropertyInfo PropertyInfo { get; }

		/// <summary>
		/// Fluently sets the column name for the property.
		/// </summary>
		/// <param name="columnName">The column name as it exists in the database.</param>
		public PropertyMap Column(string columnName)
		{
			ColumnName = columnName;
			return this;
		}

		/// <summary>
		/// Fluently sets the ignore status of the property.
		/// </summary>
		public PropertyMap Ignore()
		{
			Ignored = true;
			return this;
		}

		/// <summary>
		/// Fluently sets the read-only status of the property.
		/// </summary>
		public PropertyMap ReadOnly()
		{
			IsReadOnly = true;
			return this;
		}

		internal PropertyMap NotReadOnly()
		{
			IsReadOnly = false;
			return this;
		}

		internal PropertyMap NotIgnore()
		{
			Ignored = false;
			return this;
		}
	}

	public class IdOptions
	{
		private readonly PropertyMap _property;

		internal IdOptions(PropertyMap property)
		{
			_property = property;
			GeneratedBy = new IdOptionsSelector(property);
		}

		public IdOptionsSelector GeneratedBy { get; }

		public IdOptions Column(string columnName)
		{
			_property.Column(columnName);
			return this;
		}
	}

	public class IdOptionsSelector
	{
		private readonly PropertyMap _property;

		internal IdOptionsSelector(PropertyMap property)
		{
			_property = property;
			_property.ReadOnly()
				.Ignore();
		}

		public void AutoGenerated()
		{
		}

		public void Assigned()
		{
			_property.NotReadOnly()
				.NotIgnore();
		}
	}
}